{
 "title": "Aggregator Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "aggregator", "query": { "query": "label_values(aggregator_uuid)" } },
   {
    "name": "core",
    "query": {
     "query": "label_values(node_cpu_seconds_total{aggregator_uuid=\"$aggregator\"},cpu)"
    }
   },
   {
    "name": "listener_interval",
    "label": "Listener Interval (s)",
    "query": "5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "CPU & Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU % core $core",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "repeat": "core",
   "targets": [
    {
     "expr": "100 * (\n  1 - rate(\n        node_cpu_seconds_total{mode=\"idle\",aggregator_uuid=~\"$aggregator\",cpu=\"$core\"}[1m]\n      )\n)",
     "legendFormat": "CPU Core $core"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (\n  1 - avg by (aggregator_uuid) (\n    rate(node_cpu_seconds_total{mode=\"idle\",aggregator_uuid=~\"$aggregator\"}[1m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{aggregator_uuid=~\"$aggregator\",__name__=~\"analyze_queue_length|upload_queue_length|publish_analysis_queue_length|publish_upload_queue_length\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KVM CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * (\n  1 - avg(rate(node_cpu_seconds_total{job=\"kvm_node\",mode=\"idle\"}[5m]))\n)",
     "legendFormat": "KVM CPU"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "supervisor_process_state{aggregator_uuid=~\"$aggregator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "supervisor_process_exitcode{aggregator_uuid=~\"$aggregator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Jobs (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(analyze_jobs_processed_total{aggregator_uuid=\"$aggregator\"}[1m])*$listener_interval",
     "legendFormat": "Average Analyze Jobs"
    },
    {
     "expr": "rate(upload_jobs_processed_total{aggregator_uuid=\"$aggregator\"}[1m])*$listener_interval",
     "legendFormat": "Average Upload Jobs"
    },
    {
     "expr": "rate(publish_analysis_jobs_processed_total{aggregator_uuid=\"$aggregator\"}[1m])*$listener_interval",
     "legendFormat": "Average Publish Analysis Jobs"
    },
    {
     "expr": "rate(publish_upload_jobs_processed_total{aggregator_uuid=\"$aggregator\"}[1m])*$listener_interval",
     "legendFormat": "Average Publish Upload Jobs"
    }
   ]
  },
  { "title": "MEM and Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "100 * (\n  1 - (node_memory_MemAvailable_bytes{aggregator_uuid=~\"$aggregator\"} /\n       node_memory_MemTotal_bytes{aggregator_uuid=~\"$aggregator\"})\n)\n",
     "legendFormat": "MEM Usage"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "100 * (\n  sum(\n    node_filesystem_size_bytes{\n      fstype=\"ext4\",\n      aggregator_uuid=~\"$aggregator\"\n    }\n  )\n  -\n  sum(\n    node_filesystem_avail_bytes{\n      fstype=\"ext4\",\n      aggregator_uuid=~\"$aggregator\"\n    }\n  )\n)\n/\nsum(\n  node_filesystem_size_bytes{\n    fstype=\"ext4\",\n    aggregator_uuid=~\"$aggregator\"\n  }\n)\n",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Rx (Bytes Received) (KB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    node_network_receive_bytes_total{\n      aggregator_uuid=~\"$aggregator\",\n      device!~\"lo|docker.*|veth.*\"\n    }[1m]\n  )\n) / 1000",
     "legendFormat": "KB Received"
    }
   ]
  },
  {
   "title": "Tx (Bytes Sent) (KB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    node_network_transmit_bytes_total{\n      aggregator_uuid=~\"$aggregator\",\n      device!~\"lo|docker.*|veth.*\"\n    }[1m]\n  )\n) / 1000",
     "legendFormat": "KB Sent"
    }
   ]
  }
 ]
}